# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

  # black: Python Formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # flake8: Python PEP8 Compliance
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-bugbear'
      ]
      args: [--config=setup.cfg]

  # General Text + YAML Lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.tests/
        args: [--markdown-linebreak-ext=md]

      - id: end-of-file-fixer
        exclude: ^.tests/

      - id: check-yaml
        exclude: ^.tests/

      - id: check-added-large-files
        args: ['--maxkb=10000']

      - id: mixed-line-ending
        exclude: ^.tests/
        args: [--fix=lf]

      - id: detect-private-key

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        args: [--disable=MD013]
