# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/sphinx/source/conf.py

# Optionally declare the Python requirements required to build your docs
conda:
  environment: workflow/envs/environment.yaml

build:
   image: latest

# This part is necessary otherwise the project is not built
python:
   version: 3.8
   install:
      - method: pip
        path: .

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf
