# TIP: To check your parameters before running, use: `snakemake -c 1 print_config`

# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------

# These are the datasets, actual files, you are providing as input.

# name                 : Builds will use this to specify the input
# type                 : can be any combination of local,usher
# metadata (local)     : path to metadata for local input
# sequences (local)    : path to sequences for local input
# metadata_url (usher) : url to metadata for usher input
# pb_url (usher)       : url to protobuf for usher input
# ver_url (usher)      : url to version info for usher input

inputs:

  # A selection of publicly available samples (genbank) that have been posted
  # to https://github.com/cov-lineages/pango-designation
  - name: controls
    type:
      - local
    metadata: data/controls/metadata.tsv
    sequences: data/controls/sequences.fasta

  # An UShER base phylogeny of all publicly available samples (genbank).
  # The protobuf will be downloaded to: `data/public-latest/usher.pb.gz
  # The metadata will be downloaded to: `data/public-latest/usher.metadata.tsv
  - name: public-latest
    type:
      - usher

    # Latest: Not version controlled!
    # pb_url: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.all.masked.pb.gz
    # metadata_url: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.metadata.tsv.gz
    # ver_url: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/public-latest.version.txt

    # Date: Version controlled option
    metadata_url: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/04/02/public-2022-04-02.metadata.tsv.gz
    pb_url: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/04/02/public-2022-04-02.all.masked.pb.gz
    ver_url: http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/04/02/public-2022-04-02.version.txt

# -----------------------------------------------------------------------------
# Rule Parameters
# -----------------------------------------------------------------------------

# These are rule-based parameterization that will apply to ALL builds.
# If a parameter is not listed here, it cannot be customized.

# name    : The rule to apply the parameters to.
# <param> : The parameter name as specified in `workflow/Snakefile`.

rule_params:

  # tag : datestamp of dataset (run `nextclade dataset list` for more info)
  # dataset: The nextclade dataset to use as the reference
  - name: nextclade_dataset
    dataset: sars-cov-2
    tag: "2022-04-28T12:00:00Z"

  # nextclade_ref  : The header of the reference used by nextclade
  # custom_ref     : The header of the reference in `data/reference/reference.fasta`.
  - name: nextclade
    nextclade_ref: "MN908947 \\(Wuhan-Hu-1/2019\\)"
    custom_ref: "Wuhan/Hu-1/2019"

  # exclude_clades : Exclude strains that are recombinants of these clades
  - name: nextclade_recombinants
    exclude_clades:
        - "19" # From 2019
        - "20A" # Non-VoC From 2020
        - "20B"
        - "20C"
        - "20D"
        - "20E"
        - "20F"
        - "20G"

  # max_name_length : The maximum character length of strain names
  # clades          : Restrict parent search to these clades
  # sc2rf_args      : Additional arguments supplied to the program sc2rf
  # debug_args      : Ultra-sensitive arguments for debugging
  # primers         : Path to primers, relative to sc2rf directory.
  # primers_name    : The name of the primer set to display in output.
  - name: sc2rf
    max_name_length: 50
    clades:
      #- "20I" # Alpha
      #- "20H" # Beta
      #- "20J" # Gamma
      - "21I" # Delta
      - "21J" # Delta
      - "BA.1" # Omicron
      - "BA.2" # Omicron
      - "BA.3" # Omicron
      - "BA.4" # Omicron
      - "BA.5" # Omicron
    mutation_threshold: 0.25
    sc2rf_args: "--ansi --parents 2-4 --breakpoints 1-4 --unique 1 --max-ambiguous 20 --max-intermission-length 3 --max-intermission-count 3 --ignore-shared --show-private-mutations"
    debug_args: "--ansi --parents 1-10 --breakpoints 0-100 --unique 1 --max-ambiguous 1000 --max-intermission-length 1 --max-intermission-count 999 --enable-deletions --show-private-mutations"

  # min_len     : Ignore recombinants regions shorter than this
  # max_parents : Exlude samples with greater than this number of parents
  - name: sc2rf_recombinants
    min_len: 1000
    max_parents: 2

  # k               : The number of contextual samples to select when extracting subtrees.
  # low_memory_mode : true if the metadata should not be used, false if it should
  - name: usher_subtree
    k: 500
    low_memory_mode: true

  # cols : csv list of metadata columns to output going forwards
  - name: usher_metadata
    cols: "date,country"

  # years            : (Optional) csv list of years to include in the report
  # prev_linelist    : (Optional) Path to a previous linelist (output of rule report) for growth calculation
  # changelog        : (Optional) Path to a markdown changelog to append to the report.
  # extra_cols       : (Optional) csv list of columns from the summary to include in the linelist
  - name: report
    years: ""
    prev_linelist: ""
    changelog: ""
    extra_cols: ""


# -----------------------------------------------------------------------------
# Builds
# -----------------------------------------------------------------------------

# These are the analyses, you want to run.

# name       : A directory will be created as results/{name}
# base_input : The base phylogeny for UShER, must be an input with type "usher"

builds:

  # `controls` is the default build and will always run.
  # It uses the `controls` input as experimental samples to analyze, and places
  # them on a a base UShER phylogeny using the `public-latest` datest.

  - name: controls
    base_input: public-latest

    # Universal rule parameters can (optionally) be overridden for a specific build.
    usher_metadata:
      extra_cols: "date,country,gisaid_epi_isl,genbank_accession"
