#------------------------------------------------------------------------------#
name: Pipeline
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'autologs/**'
      - 'docs/**'
      - 'images/**'
      - 'ncov/**'
      - 'sc2rf/**'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      #------------------------------------------------------------------------#
      # env variables setup
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "CONDA_ENV_FILE=workflow/envs/environment.yaml" >> $GITHUB_ENV
          echo "CONDA_ENV_NAME=ncov-recombinant" >> $GITHUB_ENV
          echo "CI_PROFILE=profiles/ci" >> $GITHUB_ENV

      # checkout repository
      - name: checkout repo
        uses: actions/checkout@v2

      # setup conda
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge

      # install conda environment
      - name: create conda env
        run: mamba env create -f $CONDA_ENV_FILE

      # Run help
      - name: run help
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE help;

      # debugging
      #- name: (debug) tmate session
      #  uses: mxschmitt/action-tmate@v3

  #----------------------------------------------------------------------------#
  # Run the pipeline
  pipeline:
    name: Pipeline
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 60
    steps:
      #------------------------------------------------------------------------#
      # env variables setup
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "CONDA_ENV_FILE=workflow/envs/environment.yaml" >> $GITHUB_ENV
          echo "CONDA_ENV_NAME=ncov-recombinant" >> $GITHUB_ENV
          echo "CI_PROFILE=profiles/ci" >> $GITHUB_ENV
          echo "REPORT_PATH=results/controls/report.html" >> $GITHUB_ENV

      # run all
      - name: run all
        shell: bash -l {0}
        run: |
          eval "$(conda shell.bash hook)" && conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE all;
      # run report
      - name: run report
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE --report $REPORT_PATH;

      # artifact Upload
      - name: artifact report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ${{ env.REPORT_PATH }}
