#------------------------------------------------------------------------------#
name: Profile Creation
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - '*'
    paths:
      - '.github/workflows/profile_creation.yaml'
      - 'scripts/create_profile.sh'
      - 'workflow/**'
      - 'data/tutorial/**'
      - 'defaults/**'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

#------------------------------------------------------------------------------
jobs:
  #----------------------------------------------------------------------------
  tutorial:
    name: tutorial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      #------------------------------------------------------------------------
      # BEGIN: COPIED FROM install.yaml

      # env variables setup (Edit CI_PROFILE)
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "CONDA_ENV_FILE=workflow/envs/environment.yaml" >> $GITHUB_ENV
          echo "CONDA_ENV_NAME=ncov-recombinant" >> $GITHUB_ENV
          echo "CI_PROFILE=profiles/tutorial" >> $GITHUB_ENV

      # checkout repository
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # setup conda with mamba
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge

      # install conda environment
      - name: create conda env
        run: mamba env create -f $CONDA_ENV_FILE

      # run help
      - name: run help
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE help;


      # END: COPIED FROM install.yaml
      #------------------------------------------------------------------------

      - name: create profile
        shell: bash -l {0}
        run: |
          scripts/create_profile.sh --data data/tutorial;

      - name: test profile
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile my_profiles/tutorial --dry-run;

  #----------------------------------------------------------------------------
  tutorial_hpc:
    name: tututorial-hpc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      #------------------------------------------------------------------------
      # BEGIN: COPIED FROM install.yaml

      # env variables setup (Edit CI_PROFILE)
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "CONDA_ENV_FILE=workflow/envs/environment.yaml" >> $GITHUB_ENV
          echo "CONDA_ENV_NAME=ncov-recombinant" >> $GITHUB_ENV
          echo "CI_PROFILE=profiles/tutorial" >> $GITHUB_ENV

      # checkout repository
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # setup conda with mamba
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge

      # install conda environment
      - name: create conda env
        run: mamba env create -f $CONDA_ENV_FILE

      # run help
      - name: run help
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE help;


      # END: COPIED FROM install.yaml
      #------------------------------------------------------------------------

      - name: create profile
        shell: bash -l {0}
        run: |
          scripts/create_profile.sh --data data/tutorial --hpc;

      - name: test profile
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile my_profiles/tutorial-hpc --dry-run;

  #----------------------------------------------------------------------------
  tutorial_controls:
    name: tututorial-controls
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      #------------------------------------------------------------------------
      # BEGIN: COPIED FROM install.yaml

      # env variables setup (Edit CI_PROFILE)
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "CONDA_ENV_FILE=workflow/envs/environment.yaml" >> $GITHUB_ENV
          echo "CONDA_ENV_NAME=ncov-recombinant" >> $GITHUB_ENV
          echo "CI_PROFILE=profiles/tutorial" >> $GITHUB_ENV

      # checkout repository
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # setup conda with mamba
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge

      # install conda environment
      - name: create conda env
        run: mamba env create -f $CONDA_ENV_FILE

      # run help
      - name: run help
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE help;


      # END: COPIED FROM install.yaml
      #------------------------------------------------------------------------

      - name: create profile
        shell: bash -l {0}
        run: |
          scripts/create_profile.sh --data data/tutorial --controls;

      - name: test profile
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile my_profiles/tutorial-controls --dry-run;

#----------------------------------------------------------------------------
  tutorial_controls_hpc:
    name: tututorial-controls-hpc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      #------------------------------------------------------------------------
      # BEGIN: COPIED FROM install.yaml

      # env variables setup (Edit CI_PROFILE)
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
          echo "CONDA_ENV_FILE=workflow/envs/environment.yaml" >> $GITHUB_ENV
          echo "CONDA_ENV_NAME=ncov-recombinant" >> $GITHUB_ENV
          echo "CI_PROFILE=profiles/tutorial" >> $GITHUB_ENV

      # checkout repository
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # setup conda with mamba
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge

      # install conda environment
      - name: create conda env
        run: mamba env create -f $CONDA_ENV_FILE

      # run help
      - name: run help
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile $CI_PROFILE help;


      # END: COPIED FROM install.yaml
      #------------------------------------------------------------------------

      - name: create profile
        shell: bash -l {0}
        run: |
          scripts/create_profile.sh --data data/tutorial --controls --hpc;

      - name: test profile
        shell: bash -l {0}
        run: |
          conda activate $CONDA_ENV_NAME;
          snakemake --profile my_profiles/tutorial-controls-hpc --dry-run;
